// <auto-generated />
namespace Système_de_Gestion_des_Étudiants.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class RenommerColonnes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenommerColonnes));
        
        string IMigrationMetadata.Id
        {
            get { return "202503210652165_RenommerColonnes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
