// <auto-generated />
namespace Système_de_Gestion_des_Étudiants.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class CorrigerNomsColonnes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CorrigerNomsColonnes));
        
        string IMigrationMetadata.Id
        {
            get { return "202503200424304_CorrigerNomsColonnes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
